Components/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using NewsSite.Models;
using NewsSite.Data;

namespace NewsSite.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ApplicationDbContext _context;
        public CategoryMenuViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            return View(_context.Categories
                .Select(x => x)
                .Distinct()
                .OrderBy(x => x.Name));
        }
    }
}

Components/RecentNewsListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using NewsSite.Models;
using NewsSite.Data;

namespace NewsSite.Components
{
    public class RecentNewsListViewComponent : ViewComponent
    {
        private ApplicationDbContext _context;
        public RecentNewsListViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            return View(_context.News.
                OrderByDescending(x => x.Time).
                Take(3));
        }
    }
}

Components/TagCloudViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using NewsSite.Models;
using NewsSite.Data;

namespace NewsSite.Components
{
    public class TagCloudViewComponent : ViewComponent
    {
        private ApplicationDbContext _context;
        public TagCloudViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            return View(_context.Tags
                .Distinct()
                .OrderBy(x => x.Name));
        }
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using NewsSite.Data;
using NewsSite.Models;

namespace NewsSite.Controllers
{
    public class ContactController : Controller
    {
        private ApplicationDbContext dbContext;
        public ContactController(ApplicationDbContext dbContext )
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Message(Contact contact)
        {
            if (ModelState.IsValid)
            {
                dbContext.Contacts.Add(contact);
                dbContext.SaveChanges();
                return RedirectToRoute("", new { area = "", controller = "Home", action = "Index"});
            }
            else
                return View(nameof(Index), contact);
        }
    }
}

Views/Shared/Breadcrumbs.cshtml
@using NewsSite.Services
@inject BreadcrumbService BreadcrumbService

@foreach(var breadcrumb in BreadcrumbService.GetBreadcrumbs())
{
    <a asp-area="@breadcrumb.Area" asp-controller="@breadcrumb.Controller" asp-action="@breadcrumb.Action" asp-route-id="@breadcrumb.Id">@breadcrumb.Title</a>
}

Views/Shared/_Layout.cshtml
@using NewsSite.Data
@inject ApplicationDbContext DbContext

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>HomeCreditBank - @ViewData["Title"]</title>
    <link rel="stylesheet" asp-href-include="~/css/templatemo-stand-blog.css" asp-append-version="true" />
    <link rel="stylesheet" asp-href-include="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" asp-href-include="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-href-include="~/css/site.css" asp-append-version="true" />

    <style>
        .dropdown:hover .dropdown-menu {
            display: block;
            margin-top: 0;
        }
    </style>
</head>
<body>
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/static/icon.jpg" class="d-block w-100" asp-append-version=true/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link">О банке</a>
                            <ul class="dropdown-menu list-group-flush" aria-labelledby="dropdownNav">
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="Privacy">Реквизиты</a></li>
                                <li><a class="dropdown-item" asp-controller="ActivityDirections" asp-action="Index">Направления деятельности</a></li>
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="History">История</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link">Категории</a>
                            <ul class="dropdown-menu list-group-flush">
                            @foreach(var category in DbContext.Categories){
                                <li><a class="dropdown-item" asp-controller="News" asp-action="All" asp-route-category="@category.Name">@category.Name</a></li>
                            }
                            </ul>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index">Обратная связь</a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />

                </div>

            </div>
        </nav>
    </header>
    <main>
        <div class="container-lg">
            @* @await Html.PartialAsync("Breadcrumbs") *@
            @RenderBody()
        </div>
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HomeCreditBank
        </div>
    </footer>


    <script asp-src-include="~/lib/jquery/dist/jquery.min.js"></script>
    <script asp-src-include="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuPartial.cshtml
<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            @*
            <div class="col-lg-12">
                <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="#">
                        <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
                    </form>
                </div>
            </div>
            *@
            <div class="col-lg-12">
                @await Component.InvokeAsync("RecentNewsList")
            </div>
            <div class="col-lg-12">
                @await Component.InvokeAsync("CategoryMenu")
            </div>
            <div class="col-lg-12">
                @await Component.InvokeAsync("TagCloud")
            </div>
        </div>
    </div>
</div>