Models/News.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace NewsSite.Models
{
    public class News
    {
        
        public int Id {get; set; }
        [Required]
        public DateTime Time { get; set; }

        public User Author { get; set; }

        [Required]
        public string Title { get; set; }

        public string PreviewImage { get; set; }
        
        [Required]
        public string PreviewContent { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public Category Category { get; set; }

        public IEnumerable<NewsTags> Tags { get; set; }

        public IEnumerable<Comment> Comments { get; set; }

    }

    public class NewsTags
    {
        public int Id{ get; set; }

        [Required]
        public Tag Tag { get; set; }
    }
}

Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewsSite.Data;
using NewsSite.Extentions;
using NewsSite.Models;
using NewsSite.Models.ViewModels;

namespace NewsSite.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    public class NewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> manager;
        private readonly IWebHostEnvironment webHostEnvironment;
        //private readonly int PageSize = 6;

        public NewsController(ApplicationDbContext context, UserManager<User> manager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.manager = manager;
            this.webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(nameof(AdminList), _context.News.OrderByDescending(x => x.Id).ToList());
        }

        [HttpGet]

        public IActionResult AdminList()
        {
            return View(_context.News.OrderByDescending(x => x.Id).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            _context.Entry(news).Collection(x => x.Tags).Load();
            foreach (var tag in news.Tags)
                _context.Entry(tag).Reference(x => x.Tag).Load();
            _context.Entry(news).Reference(x => x.Category).Load();

            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_context.Categories.Select(x => x), nameof(Category.Id), nameof(Category.Name));
            return View(new EditNewsViewModel
            {

            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EditNewsViewModel newsViewModel)
        {
            if (ModelState.IsValid)
            {
                var news = new News
                {
                    Time = newsViewModel.Time,
                    Title = newsViewModel.Title,
                    PreviewContent = newsViewModel.PreviewContent,
                    Content = newsViewModel.Content,
                    Author = await manager.GetUserAsync(HttpContext.User)
                };
                if (int.TryParse(newsViewModel.Category, out int Categoty_id))
                {
                    if (!_context.Categories.Any(x => x.Id == Categoty_id))
                    {
                        ModelState.AddModelError(string.Empty, "Не найдено ни одной категории");
                        return View(newsViewModel);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Не найдено ни одной категории");
                    return View(newsViewModel);
                }
                news.Category = _context.Categories.First(x => x.Id == Categoty_id);
                news.PreviewImage = UploadedFile(newsViewModel);

                var tags = from tag in newsViewModel.Tags.Split(',') select tag.Trim().FirstCharToUpper();

                var tags_objects =
                    from tag in tags
                    join tag_object in _context.Tags
                    on tag equals tag_object.Name into tags_context_objects
                    from tag_object in tags_context_objects.DefaultIfEmpty()
                    select tag_object ?? new Tag() { Name = tag };

                news.Tags = tags_objects.Select(x => new NewsTags() { Tag = x }).ToList();
                _context.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(newsViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }

            _context.Entry(news).Collection(x => x.Tags).Load();
            foreach (var tag in news.Tags)
                _context.Entry(tag).Reference(x => x.Tag).Load();
            _context.Entry(news).Reference(x => x.Category).Load();

            ViewBag.Categories = new SelectList(_context.Categories.Select(x => x), nameof(Category.Id), nameof(Category.Name));
            return View(new EditNewsViewModel(news));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditNewsViewModel newsViewModel)
        {

            if (ModelState.IsValid)
            {

                var news = _context.News.Find(newsViewModel.Id);
                if (news == null)
                {
                    return NotFound();
                }

                _context.Entry(news).Collection(x => x.Tags).Load();
                foreach (var tag in news.Tags)
                    _context.Entry(tag).Reference(x => x.Tag).Load();
                _context.Entry(news).Reference(x => x.Category).Load();

                if (news.Time != newsViewModel.Time)
                    news.Time = newsViewModel.Time;
                if (news.Title != newsViewModel.Title)
                    news.Title = newsViewModel.Title;
                if (news.PreviewContent != newsViewModel.PreviewContent)
                    news.PreviewContent = newsViewModel.PreviewContent;

                if (int.TryParse(newsViewModel.Category, out int Categoty_id))
                {
                    if (!_context.Categories.Any(x => x.Id == Categoty_id))
                    {
                        ModelState.AddModelError(string.Empty, "Не найдено ни одной категории");
                        return View(newsViewModel);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Не найдено ни одной категории");
                    return View(newsViewModel);
                }
                var Category = _context.Categories.First(x => x.Id == Categoty_id);
                if (news.Category != Category)
                    news.Category = Category;
                if (newsViewModel.PreviewImage != null)
                    news.PreviewImage = UploadedFile(newsViewModel);

                var tags = from tag in newsViewModel.Tags.Split(',') select tag.Trim().FirstCharToUpper();

                var tag_context = _context.Tags;

                var tags_objects =
                    from tag in tags
                    join tag_object in tag_context
                    on tag equals tag_object.Name into tags_context_objects
                    from tag_object in tags_context_objects.DefaultIfEmpty()
                    select tag_object ?? new Tag() { Name = tag };


                _context.NewsTags.RemoveRange(news.Tags);
                news.Tags = tags_objects.Distinct().Select(x => new NewsTags() { Tag = x }).ToList();
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

                //Автора не трогаем

                /*
                var news = new News
                {
                    Time = newsViewModel.Time,
                    Title = newsViewModel.Title,
                    PreviewContent = newsViewModel.PreviewContent,
                    Content = newsViewModel.Content,
                    Author = await manager.GetUserAsync(HttpContext.User)
                };
                */
                /*
                if (int.TryParse(newsViewModel.Category, out int Categoty_id))
                {
                    if (!_context.Categories.Any(x => x.Id == Categoty_id))
                    {
                        ModelState.AddModelError(string.Empty, "Не найдено ни одной категории");
                        return View(newsViewModel);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Не найдено ни одной категории");
                    return View(newsViewModel);
                }
                */
                /*
                news.Category = _context.Categories.First(x => x.Id == Categoty_id);
                news.PreviewImage = UploadedFile(newsViewModel);

                var tags = from tag in newsViewModel.Tags.Split(',') select tag.Trim().FirstCharToUpper();

                var tags_objects =
                    from tag in tags
                    join tag_object in _context.Tags
                    on tag equals tag_object.Name into tags_context_objects
                    from tag_object in tags_context_objects.DefaultIfEmpty()
                    select tag_object ?? new Tag() { Name = tag };

                news.Tags = tags_objects.Select(x => new NewsTags() { Tag = x }).ToList();
                _context.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                */
            }
            return View(newsViewModel);



            /*

            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try

Components/NewsCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using NewsSite.Models;
using NewsSite.Data;

namespace NewsSite.Components
{
    public class NewsCardViewComponent : ViewComponent
    {
        private ApplicationDbContext _context;
        public NewsCardViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke(News news)
        {
            return View(news);
        }
    }
}

Views/News/All.cshtml
@model NewsListViewModel
@{
    string hasPreviousPage = Model.PageViewModel.HasPreviousPage ? "" : "disabled";
    string hasNextPage = Model.PageViewModel.HasNextPage ? "" : "disabled";
}

<section class="blog-posts grid-system">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row gy-5">
                        @foreach (var news in Model.News)
                        {
                            @await Component.InvokeAsync("NewsCard", news)
                        }
                    </div>
                </div>
                <div class="d-grid gap-2 d-sm-flex justify-content-center btn-group btn-group-eq-size mt-5">
                    <a asp-action="All"
                       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                       asp-route-category=@Model.Category
                       asp-route-tag=@Model.Tag
                       class="btn btn-outline-dark @hasPreviousPage">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Назад
                    </a>

                    <a asp-action="All"
                       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                       asp-route-category=@Model.Category
                       asp-route-tag=@Model.Tag
                       class="btn btn-outline-dark @hasNextPage">
                        Вперед
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </a>

                </div>
            </div>
            @await Html.PartialAsync("_MenuPartial")
        </div>
    </div>
</section>

Views/News/Post.cshtml
@model News
@inject SignInManager<User> SignInManager
@{
    string NickName = Model.Author?.NickName ?? "Author";
}
<section class="blog-posts grid-system">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-post">
                                @if (!string.IsNullOrEmpty(Model.PreviewImage))
                                {
                                    <div class="blog-thumb">
                                        <img src="~/images/@Model.PreviewImage" alt="">
                                    </div>
                                }
                                <div class="down-content">
                                    <span>@Model.Category.Name</span>
                                    <a asp-controller="News" asp-action="Post" asp-route-id="@Model.Id"><h4>@Model.Title</h4></a>
                                    <ul class="post-info">
                                        <li><a href="#">@NickName</a></li>
                                        <li><a href="#">@Model.Time.ToString("D")</a></li>
                                    </ul>
                                    
                                    <div class="post-content">@Html.Raw(Model.Content)</div>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <post-tags elements="@Model.Tags"></post-tags>
                                            </div>
                                            <div class="col-6">
                                                <ul class="post-share">
                                                    <li><i class="fa fa-share-alt"></i></li>
                                                    <li><a href="#">Facebook</a>,</li>
                                                    <li><a href="#">Twitter</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-lg-12">
                            <div class="sidebar-item comments">
                                <div class="sidebar-heading">
                                    <h2>Комментарии</h2>
                                </div>
                                <div class="content">
                                    <ul class="vstack">
                                        @foreach(var comment in Model.Comments){
                                        <li>
                                            <div>
                                                <h4>@comment.User.NickName.Trim()<span>@comment.Time.ToString("g")</span></h4>
                                                <p>@comment.Content.Trim()</p>
                                            </div>
                                        </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="col-lg-12">
                                <div class="sidebar-item submit-comment">
                                    <div class="sidebar-heading">
                                        <h2>Оставьте комментарий</h2>
                                    </div>
                                    <div class="content">
                                        <form asp-controller="News" asp-action="Comment" asp-route-NewsId="@Model.Id" method="post">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <textarea name="Content" rows="6" placeholder="Ваш комментарий" required></textarea>
                                                </div>
                                                <div class="col-lg-12">
                                                    <button type="submit" class="main-button">Submit</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            @await Html.PartialAsync("_MenuPartial")
        </div>
    </div>
</section>