Models/ActivityDirections.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace NewsSite.Models
{
    public class ActivityDirections
    {
        
        public int Id {get; set; }

        [Required]
        public string Title { get; set; }

        public string PreviewImage { get; set; }
        
        [Required]
        public string PreviewContent { get; set; }

        [Required]
        public string Content { get; set; }

    }

}

Models/ViewModels/ActivityDirectionsViewModel.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Linq;

namespace NewsSite.Models.ViewModels
{
    public class ActivityDirectionsViewModel
    {
        public int Id { get; set; }
        
        [Required]
        [Display(Name = "Заголовок")]
        public string Title { get; set; }

        [Display(Name = "Основная картинка")]
        public IFormFile PreviewImage { get; set; }

        [Required]
        [Display(Name = "Описание")]
        public string PreviewContent { get; set; }

        [Required]
        [Display(Name = "Содержание")]
        public string Content { get; set; }


        public ActivityDirectionsViewModel()
        {

        }

        public ActivityDirectionsViewModel(ActivityDirections activityDirections)
        {
            this.Id = activityDirections.Id;
            this.Title = activityDirections.Title;
            this.PreviewContent = activityDirections.PreviewContent;
            this.Content = activityDirections.Content;
        }
    }
}

Areas/Admin/Controllers/ActivityDirectionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsSite.Data;
using NewsSite.Models;
using NewsSite.Models.ViewModels;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NewsSite.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    public class ActivityDirectionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ActivityDirectionsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View("List", _context.ActivityDirections.ToList());
        }

        // GET: ActivityDirectionsController/Create
        public ActionResult Create()
        {
            ViewBag.Action = "Create";
            return View("Edit");
        }

        // POST: ActivityDirectionsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("PreviewContent,Title,Content,PreviewImage")] ActivityDirectionsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var activityDirections = new ActivityDirections
                {
                    Title = model.Title,
                    PreviewContent = model.PreviewContent,
                    Content = model.Content,
                    PreviewImage = UploadedFile(model)
                };


                _context.Add(activityDirections);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            return View("Edit",model);
        }

        // GET: ActivityDirectionsController/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.Action = "Edit";
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.ActivityDirections.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: ActivityDirectionsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,PreviewContent,Title,Content")] ActivityDirections model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(new ActivityDirectionsViewModel(model));
        }

        // GET: ActivityDirectionsController/Delete/5
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var ActivityDirections = _context.ActivityDirections
                .FirstOrDefault(m => m.Id == id);
            if (ActivityDirections == null)
            {
                return NotFound();
            }

            return View(ActivityDirections);
        }

        // POST: ActivityDirectionsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            var ActivityDirections =  _context.ActivityDirections.Find(id);
            _context.ActivityDirections.Remove(ActivityDirections);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult List()
        {
            return View(_context.ActivityDirections.Select(x => x));
        }

        public async Task<IActionResult> Post(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.ActivityDirections.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        private string UploadedFile(ActivityDirectionsViewModel model)
        {
            string uniqueFileName = null;
            if (model.PreviewImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");

                uniqueFileName = Guid.NewGuid().ToString() + Path.GetExtension(model.PreviewImage.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using var fileStream = new FileStream(filePath, FileMode.Create);
                model.PreviewImage.CopyTo(fileStream);
            }
            return uniqueFileName;
        }

        private bool ModelExists(int id)
        {
            return _context.ActivityDirections.Any(e => e.Id == id);
        }
    }
}

Controllers/ActivityDirectionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsSite.Data;
using NewsSite.Models;
using NewsSite.Models.ViewModels;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NewsSite.Controllers
{
    public class ActivityDirectionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ActivityDirectionsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }



        // GET: ActivityDirectionsController
        public ActionResult Index()
        {
            return View(_context.ActivityDirections.Select(x => x));
        }

        public async Task<IActionResult> Post(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.ActivityDirections.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        /*
        // GET: ActivityDirectionsController/Create
        public ActionResult Create()
        {
            ViewBag.Action = "Create";
            return View("Edit");
        }

        // POST: ActivityDirectionsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("PreviewContent,Title,Content,PreviewImage")] ActivityDirectionsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var activityDirections = new ActivityDirections
                {
                    Title = model.Title,
                    PreviewContent = model.PreviewContent,
                    Content = model.Content,
                    PreviewImage = UploadedFile(model)
                };


                _context.Add(activityDirections);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            return View("Edit",model);
        }

        // GET: ActivityDirectionsController/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.Action = "Edit";
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.ActivityDirections.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: ActivityDirectionsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,PreviewContent,Title,Content")] ActivityDirections model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(new ActivityDirectionsViewModel(model));
        }

        // GET: ActivityDirectionsController/Delete/5
        public ActionResult Delete(int id)
        {

            return View();
        }

        // POST: ActivityDirectionsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult List()
        {
            return View(_context.ActivityDirections.Select(x => x));
        }

        

        private string UploadedFile(ActivityDirectionsViewModel model)
        {
            string uniqueFileName = null;
            if (model.PreviewImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");

                uniqueFileName = Guid.NewGuid().ToString() + Path.GetExtension(model.PreviewImage.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using var fileStream = new FileStream(filePath, FileMode.Create);
                model.PreviewImage.CopyTo(fileStream);
            }
            return uniqueFileName;
        }

        private bool ModelExists(int id)
        {
            return _context.ActivityDirections.Any(e => e.Id == id);
        }
        */
    }
}

Areas/Admin/Views/ActivityDirections/Delete.cshtml
@model NewsSite.Models.ActivityDirections

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/ActivityDirections/Edit.cshtml
@model ActivityDirectionsViewModel
@{
    ViewData["Title"] = "Edit";
    string Action = (string)ViewBag.Action ?? "Create";
}

<h1>Edit</h1>

<h4>News</h4>
<hr />
<div class="row">
    <div class="">
        <form asp-action="@Action" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreviewContent" class="control-label"></label>
                <textarea asp-for="PreviewContent" class="form-control"></textarea>
                <span asp-validation-for="PreviewContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreviewImage" class="control-label"></label>
                <input asp-for="PreviewImage" class="form-control" type="file"/>
                <span asp-validation-for="PreviewImage" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 clearfix">
                <input type="submit" value="@Action" class="btn btn-primary float-end" />
            </div>
            <script>
                CKEDITOR.replace('Content');
            </script>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/ActivityDirections/Index.cshtml
@model IEnumerable<ActivityDirections>

<section class="blog-posts grid-system">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        @*В виде карточек (потом переделать во что то красивое) *@
                        @foreach (var obj in Model)
                        {
                            <div class="col-lg-6">
                                <div class="blog-post">
                                    @if (!string.IsNullOrEmpty(obj.PreviewImage))
                                    {
                                        <div class="blog-thumb">
                                            <img src="~/images/@obj.PreviewImage" alt="">
                                        </div>
                                    }
                                    <div class="down-content">
                                        <a asp-controller="ActivityDirections" asp-action="Post" asp-route-id="@obj.Id"><h4>@obj.Title</h4></a>
                                        <p>@obj.PreviewContent</p>
                                    </div>
                                </div>
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Areas/Admin/Views/ActivityDirections/List.cshtml
@model IEnumerable<NewsSite.Models.ActivityDirections>

@{
    ViewData["Title"] = "List";
}

<h1>Направления деятельности</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreviewImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreviewContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreviewImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreviewContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>